# Generated by Django 5.1.1 on 2025-01-21 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingreceip',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(default='No pagado', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Encargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='actual_cost_of_product',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingreceip',
            name='status_of_shopping',
            field=models.CharField(default='No pagado', max_length=100),
        ),
    ]
