# Generated by Django 5.1.1 on 2025-01-21 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shoppingreceip_buy_date_alter_order_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuyed',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
