# Generated by Django 5.1.1 on 2025-01-21 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productbuyed_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingreceip',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
