# Generated by Django 5.1.1 on 2025-01-22 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shoppingreceip_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverreceip',
            name='deliver_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productreceived',
            name='amount_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
