# Generated by Django 5.1.1 on 2025-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deliverreceip_deliver_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status_of_processing',
            field=models.CharField(default='Enviado', max_length=100),
        ),
    ]
