# Generated by Django 5.1.1 on 2025-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productreceived_deliver_receip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_image', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_picture',
        ),
        migrations.RemoveField(
            model_name='deliverreceip',
            name='deliver_picture',
        ),
        migrations.AlterField(
            model_name='deliverreceip',
            name='status',
            field=models.CharField(default='Enviado', max_length=100),
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_picture',
        ),
        migrations.AddField(
            model_name='product',
            name='product_pictures',
            field=models.ManyToManyField(to='api.evidenceimages'),
        ),
        migrations.AddField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.ManyToManyField(to='api.evidenceimages'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_picture',
            field=models.ManyToManyField(to='api.evidenceimages'),
        ),
    ]
