# Generated by Django 5.1.1 on 2025-02-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_evidenceimages_remove_product_product_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceimages',
            old_name='url_image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='evidenceimages',
            name='name',
        ),
    ]
