# Generated by Django 5.1.1 on 2025-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_url_image_evidenceimages_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceimages',
            name='public_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
