# Generated by Django 5.1.1 on 2025-02-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_evidenceimages_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Encargado', max_length=100),
        ),
    ]
