# Generated by Django 5.1.1 on 2025-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='taxes',
            field=models.FloatField(default=0),
        ),
    ]
