# Generated by Django 5.1.1 on 2025-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_product_shop_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_picture',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pictures',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
    ]
