# Generated by Django 5.1.1 on 2025-03-08 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_deliverreceip_deliver_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
